name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Copy repository to Pi
      run: |
        sudo cp -r $GITHUB_WORKSPACE /root/projects

    - name: Install NPM dependencies
      run: |
        cd /root/projects/IoT-Smart-Stairs
        npm install

    - name: Build the project
      run: |
        cd /root/projects/IoT-Smart-Stairs
        npm run build

    - name: Start the application with pm2
      run: |
        cd /root/projects/IoT-Smart-Stairs
        pm2 start ecosystem.config.js --env production
