name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy repository to Pi
      run: |
        sudo cp -r $GITHUB_WORKSPACE /root/repo

    - name: Navigate to project directory
      working-directory: /root/repo

    - name: Install NPM dependencies
      run: |
        cd /root/repo
        npm install

    - name: Build the project
      run: |
        cd /root/repo
        npm run build

    - name: Start the application with pm2
      run: |
        cd /root/repo
        pm2 start ecosystem.config.js --env production
